Notifications
eXpansionPluginPack/eXpansion2 pull request #293
Opened 2018-02-26 12:54 UTC by reaby

Added notifications for gamecurrency bundle.

2018-02-26 16:15 UTC, oliverde8 requested changes

2018-02-26 16:15 UTC, oliverde8 commented on src/eXpansion/Bundle/WidgetBestCheckpoints/Plugins/BestCheckpoints.php
> +            echo "load\n";
Hmmm :smile:

2018-02-26 16:28 UTC, reaby commented on src/eXpansion/Bundle/WidgetBestCheckpoints/Plugins/BestCheckpoints.php
> +            echo "load\n";
:D

2018-02-27 10:15 UTC, oliverde8 commented
This has been already merged in #295

2018-02-27 10:15 UTC, closed without merging