Improvements to the Local Records & Core Data provider
eXpansionPluginPack/eXpansion2 pull request #323
Opened 2018-04-07 11:17 UTC by oliverde8

* Allow listening to multiple data providers at the time (so widgets can listen to race & laps listeners)
* Updated widgets to handle the race & laps records
* Update Records window to show race & lap records
* Fixed issue with lost events at eXpansion startup

2018-04-07 12:48 UTC, reaby requested changes

2018-04-07 12:48 UTC, reaby commented on src/eXpansion/Framework/Core/Services/DataProviderManager.php
> +            var_dump($provider);
remove debug

2018-04-08 07:30 UTC, oliverde8 commented
Removed the debug 😄

2018-04-08 13:29 UTC, reaby approved these changes

2018-04-08 13:29 UTC, merged